export const BOTTOM_GAP = 11;
export const TOP_GAP = 13;
export const POINTER_HEIGHT = 6;
export const ZERO_WIDTH_SPACE = '\ufeff';
export const COLOR_HEX = ['#F7A586', '#FAFD22', '#9BEBAA', '#9BC1EB'];
export const COLOR_NAMES = ['red', 'yellow', 'green', 'blue'];
export const NODE_TYPE_COMMENT = 8;
export const NODE_TYPE_TEXT = 3;
export const NODE_TYPE_ELEMENT = 1;
